name: CI

on: push

jobs:
  lint:
    name: Run Lint, and check format.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno lint src
      - run: deno fmt --check src
