name: CI

on: push

jobs:
  lint:
    name: Run Lint, and check format.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno lint
      - run: deno fmt --check
